"""initial schema

Revision ID: 8e5887125ec7
Revises: 
Create Date: 2026-09-10 17:50:42.997515

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e5887125ec7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooperatives',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=160), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cooperatives')),
    sa.UniqueConstraint('code', name=op.f('uq_cooperatives_code'))
    )
    op.create_table('producers',
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='gender', native_enum=False, length=12), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('registered_at', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_producers_cooperative_id_cooperatives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producers'))
    )
    with op.batch_alter_table('producers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producers_cooperative_id'), ['cooperative_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_producers_national_id'), ['national_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('agent', 'manager', 'exporter', 'regulator', 'admin', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooperative_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_users_cooperative_id_cooperatives'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_cooperative_id'), ['cooperative_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('compliance_reports',
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('parcel_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_key', sa.String(length=300), nullable=True),
    sa.Column('geojson_key', sa.String(length=300), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_compliance_reports_cooperative_id_cooperatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_compliance_reports_generated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_reports'))
    )
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_reports_cooperative_id'), ['cooperative_id'], unique=False)

    op.create_table('parcels',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=True),
    sa.Column('cooperative_id', sa.UUID(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('planting_year', sa.SmallInteger(), nullable=True),
    sa.Column('crop', sa.String(length=40), nullable=False),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('collection_method', sa.Enum('walk', 'vertices', 'manual', 'import', name='collectionmethod', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('mobile', 'web', 'import', name='parcelsource', native_enum=False, length=12), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='parcelstatus', native_enum=False, length=12), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], name=op.f('fk_parcels_collected_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_parcels_cooperative_id_cooperatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], name=op.f('fk_parcels_producer_id_producers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parcels'))
    )
    # NB : l'index spatial GiST `idx_parcels_geometry` est créé automatiquement
    # par GeoAlchemy2 lors du op.create_table (colonne Geometry, spatial_index=True).
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcels_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_parcels_cooperative_id'), ['cooperative_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcels_producer_id'), ['producer_id'], unique=False)

    op.create_table('sync_batches',
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('client_batch_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'partial', 'done', 'failed', name='syncstatus', native_enum=False, length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_batches_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_batches')),
    sa.UniqueConstraint('device_id', 'client_batch_id', name='uq_sync_batches_device_client')
    )
    with op.batch_alter_table('sync_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_batches_device_id'), ['device_id'], unique=False)

    op.create_table('alerts',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('new_deforestation', 'protected_encroachment', 'data_gap', name='alerttype', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity', native_enum=False, length=12), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('message', sa.String(length=400), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_alerts_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_parcel_id'), ['parcel_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('provider_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forest_cover_2020_pct', sa.Float(), nullable=True),
    sa.Column('forest_cover_current_pct', sa.Float(), nullable=True),
    sa.Column('forest_loss_ha', sa.Float(), nullable=False),
    sa.Column('loss_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ndvi_series', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('protected_area_overlap_ha', sa.Float(), nullable=False),
    sa.Column('deforestation_detected', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_analysis_runs_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_parcel_id'), ['parcel_id'], unique=False)

    op.create_table('compliance_scores',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel', native_enum=False, length=10), nullable=False),
    sa.Column('eudr_status', sa.Enum('compliant', 'at_risk', 'non_compliant', name='eudrstatus', native_enum=False, length=16), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_compliance_scores_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_compliance_scores_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_scores'))
    )
    with op.batch_alter_table('compliance_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_scores_parcel_id'), ['parcel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_scores_parcel_id'))

    op.drop_table('compliance_scores')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_parcel_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_parcel_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('sync_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_batches_device_id'))

    op.drop_table('sync_batches')
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcels_producer_id'))
        batch_op.drop_index(batch_op.f('ix_parcels_cooperative_id'))
        batch_op.drop_index(batch_op.f('ix_parcels_code'))

    op.drop_table('parcels')
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_reports_cooperative_id'))

    op.drop_table('compliance_reports')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_cooperative_id'))

    op.drop_table('users')
    with op.batch_alter_table('producers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producers_national_id'))
        batch_op.drop_index(batch_op.f('ix_producers_cooperative_id'))

    op.drop_table('producers')
    op.drop_table('cooperatives')
    # ### end Alembic commands ###
